### ISSUE TITLE
onChange with entity-form

### ISSUE THREAD

**Issue by codezion** [SpoonX/aurelia-form#103]
For UI logic it is valuable to know if entity-form is modified by user. Could that be added like ability to define onChange handler for it?

**Comment by bas080** [comment]
One can add property observers to the entity. Dom events are also propagated, this allows one to define a native dom `onchange=fn()`.

**Comment by codezion** [comment]
Thanks for pointing to the right and new direction. Here the exact code I got working, other event names didn't, but that is enough. Both events are needed to cover different types of the form elements.
```
<entity-form
      entity.bind="myEntity"
      keypress.delegate="onChange($event)"
      change.delegate="onChange($event)"
```
and in the js:
```
onChange(event)
{
  this.changed = true;
  return true;
}
```

**Comment by RWOverdijk** [comment]
Thanks for that :) I'm closing this ticket now.
