### ISSUE TITLE
Aurelia-Form 0.4.0 using ValidationEngine which is not to be found

### ISSUE THREAD

**Issue by shaunnmukmen** [SpoonX/aurelia-form#105]
Tried to use Aurelia-Form 0.4.0. Got error in Form.js where the code is trying to use ValidationEngine.

_this.reporter = _aureliaValidatejs.ValidationEngine.getValidationReporter(model);

ValidationEngine is not to be found in aurelia-validatejs or aurelia-validation.

**Comment by RWOverdijk** [comment]
@bas080 Could you spend some time on this? (after finishing your other tasks). If it takes too long, talk to me on gitter.

**Comment by bas080** [comment]
@shaunnmukmen, The `Form` class is outdated. It's best to not use it.

Will have to
- [ ] remove Form class from documentation
- [ ] remove the Form class from aurelia-form

**Comment by RWOverdijk** [comment]
Closing this due to added support in the next version of form. Questions? Feel free to ask :)
