### ISSUE TITLE
Set select value when not given

### ISSUE THREAD

**Issue by VMBindraban** [SpoonX/aurelia-form#18]
You must always define a value:

``` js
  operatorElement = {
    key    : 'foo',
    type   : 'select',
    options: [
      {name: 'foo', value: 'foo'}
    ]
  }
```

When not given a `value`, generate it based on `name`? (like the html `option` tag)

**Comment by RWOverdijk** [comment]
`options: ['foo', 'bar', 'bat']` should also work.

**Comment by bas080** [comment]
you can do the following.

``` js
let options = [
  'bar',
  {name: 'baz'},
  {value: 'boo'},
  {name: 'rat', value: 'tata'}
];
```

**Comment by bas080** [comment]
PR: https://github.com/SpoonX/aurelia-form/pull/32

**Comment by bas080** [comment]
https://github.com/SpoonX/aurelia-form/pull/47 has been merged which implements this feature.
