### ISSUE TITLE
isValid bindable for <aurelia-form> and <entity-form> components

### ISSUE THREAD

**Issue by bas080** [SpoonX/aurelia-form#187]
I would like to be able to write the following.

```html

<entity-form entity.bind="user" isValid.bind="isValid"></entity-form>

```

I can then use the isValid on my view model to enable of disable a custom submit button.

**Comment by RWOverdijk** [comment]
@bas080 aurelia-form will need a bindable, as would entity-form. It needs to be updated with every validation call in aurelia-form.js, should be simple enough to implement :)
