### ISSUE TITLE
Schema-form

### ISSUE THREAD

**Issue by RWOverdijk** [SpoonX/aurelia-form#188]
Recently someone has asked where schema-form went. It has been removed in favor of entity-form and verbose components.

If you use schema-form and wish to see it re-introduced, please leave a comment or emoji response on this issue so we know how much of a priority this should be.

Thanks!

**Comment by s-hoff** [comment]
I personally consider schema-form to mainly have two advantages:

First, we can get some of the form definition such as input type, show/hide or disabled state from some kind of backend or configuration module at run time. This would be useful when one would want to, for example, sell the product to multiple clients and have it customized to their structure without having to create and maintain different builds for each of them.

Second, I cannot see how you would e.g. make the state of one field dependent on the state of another using `entity-form`. For example, disabling a part of the form until the user explicitly turns it on with a checkbox. or when you have a select whose options depend on the editing context. `entity-form`, as great as it is, seems to be a bit too static here and a schema-form could handle a lot of those use cases requiring more flexibility.

Here, having a schema, especially when done using object notation or maps, comes in very handy without having to resort to manually building with `aurelia-form`.
