### ISSUE TITLE
[Feature Resuest](decorators,entity-form): Add decorators for select elements

### ISSUE THREAD

**Issue by s-hoff** [SpoonX/aurelia-form#190]
The `form-select` component has the attributes `multiple`, `selectOptions` and `optionLabel`: https://aurelia-form.spoonx.org/component/form-select.html
The `form-group` component can pass them on: https://aurelia-form.spoonx.org/component/form-group.html
But there are no [decorators](https://aurelia-form.spoonx.org/decorators.html) for them, meaning `entity-form` does not support it.

Found in Version 1.1.5

**Comment by RWOverdijk** [comment]
I'm not sure I understand. Which decorators / attributes do you mean?

**Comment by s-hoff** [comment]
I rephrased the issue to clarify.

**Comment by bas080** [comment]
@s-hoff, I think you can use the options decorator for that.

**Comment by s-hoff** [comment]
Actually, options is another attribute altogether. All elements pass it to [prefix](https://github.com/SpoonX/aurelia-form/blob/master/src/attribute/prefixed.js), which looks like it just adds some extra css classes.

**Comment by RWOverdijk** [comment]
@s-hoff You're right, there's no decorator for that yet. It's really simple to create a decorator for that, and pass the options through (selectOptions). Would you like to give it a go? I can give you some pointers on gitter :)

**Comment by s-hoff** [comment]
Working on it now :)
