### ISSUE TITLE
Validation of aurelia-form does not work when the entity is replaced

### ISSUE THREAD

**Issue by t03apt** [SpoonX/aurelia-form#193]
I think validation does not work because aureliaForm.mapped goes out of sync of aureliaForm.formGroups.
Screencast: https://www.screencast.com/t/7NQfnhTJUpt (I can't record audio at the moment.)
WARN [aurelia-form-validation] Group not found for validation error on 'age2'.

You can easily reproduce the same:
Source code: https://gitlab.com/t03apt/aurelia-form-demo-typescript-webpack
Branch: troubleshooting-au-form
NOTE: my-entity-form is almost identical with entity-form. I just needed to add an auForm property to be able to get the aurelia-form object.

aureliaForm.formGroupsChanged is not getting fired. I think formGroupsChanged combined with a  CollectionObserver could fix this.

**Comment by RWOverdijk** [comment]
It doesn't get fired because it doesn't change in terms of reference, so that makes sense.

What I think we can do here, is implement a manual refresh of some sort. Your case is special in that you want dynamic validation, so maybe triggering a method when you change the groups would suffice? Otherwise it can probably watch the count or something. Interesting case either way.

**Comment by t03apt** [comment]
a) I have tried using aurelia observers to subscribe any changes related to formGroups.
It did not work. formGroups was changing and subscribe was not fired.

```
  @observable private auForm: AureliaForm;
  private formGroupsChangedSubscriptions: Array<Disposable> = [];
  auFormChanged() {
    this.formGroupsChangedSubscriptions.forEach((o) => o.dispose());
    this.formGroupsChangedSubscriptions = [];

    let auForm = this.auForm;
    if (auForm) {
      let callback = () => {
        for (let key of Object.getOwnPropertyNames(auForm.mapped)) {
          delete auForm.mapped[key];
        }
        auForm.formGroupsChanged();
      };
      this.formGroupsChangedSubscriptions.push(this.bindingEngine
        .collectionObserver(auForm.formGroups)
        .subscribe(callback));

      this.formGroupsChangedSubscriptions.push(this.bindingEngine
        .propertyObserver(auForm, "formGroups")
        .subscribe(callback));
    }
  }
```

b) This workaround works.
  ```
private keepMappedInSync;
private oldFormGroups: Array<any> = [];
private oldFormGroupsJson: string;
attached() {
  this.keepMappedInSync = setInterval(() => {
    let auForm = this.auForm;
    if (auForm) {
      let currentFormGroups: Array<any> = auForm.formGroups;
      let currentFormGroupsJson = JSON.stringify(currentFormGroups.map(o => o.name))
      if (!(
        currentFormGroupsJson === this.oldFormGroupsJson &&
        this.oldFormGroups.length === currentFormGroups.length &&
        this.oldFormGroups.every((o) => currentFormGroups.includes(o)))
      ) {
        for (let key of Object.getOwnPropertyNames(auForm.mapped)) {
          delete auForm.mapped[key];
        }
        auForm.formGroupsChanged();
        this.oldFormGroups = [...currentFormGroups];
        this.oldFormGroupsJson = currentFormGroupsJson;
      }
    }
  }, 100);
}

  detached() {
    clearInterval(this.keepMappedInSync);
  }
```
c) I think it would be better to remove 'mapped' property and pass a proxy to getController and ValidationRenderer. So that ValidationRenderer would have a reference only for a proxy. It could make a call like proxy.getGroup().
Example: ValidationRenderer.js
```
  getGroup({propertyName, valid}) {
    if (valid) {
      return;
    }
    let group = this.proxy.getGroup(propertyName);
    if (!group) {
      logger.warn(`Group not found for validation error on '${propertyName}'.`);
      return;
    }
    return group;
  }
```
aurelia-form.js
```
    if (validation && validation.controller) {
      let proxy = {
        getGroup: (propertyName) => this.formGroups.find(group => group.name == propertyName)
      };
      this.validationController = validation.controller.getController(proxy, validation.trigger);
      this.validateTrigger = validation.controller.getTriggers();
    }
```
What do you think about it?

**Comment by t03apt** [comment]
_I have edited b) a few times. It is an ugly workaround._

**Comment by RWOverdijk** [comment]
@t03apt I like the out-of-the-box way of thinking, but I think we can make it easier.

https://github.com/SpoonX/aurelia-form/blob/master/src/component/aurelia-form.js#L123 Does this get called for you? It does for me, so it might be interesting to use this location to trigger any other validation updates we might want (based on the current state).

**Comment by t03apt** [comment]
> https://github.com/SpoonX/aurelia-form/blob/master/src/component/aurelia-form.js#L123 Does this get called for you?

I have found an interesting thing.
If I replace the entity with another one which has the same amount of properties then it is not triggered. See: https://www.screencast.com/t/vfhJoyqjBcPr
But if I replace it with an entity that has more properties than the previous one then it gets triggered.
See: https://www.screencast.com/t/B2S3IjL5q

It looks like aurelia repeat.for is reusing some existing formGroup elements for new entities.
_I have pushed my code to the same gitlab repo. Same branch._

**Comment by RWOverdijk** [comment]
Probably because it uses an array observer. If the length changes, an update is triggered. Which doesn't happen. We'll need more specific observers. I'll take a look when I have time, I'm a bit more busy nowadays.

**Comment by t03apt** [comment]
Or we could go with the proxy approach. :)

**Comment by RWOverdijk** [comment]
@t03apt I think that's still too complicated to be honest. All we want to do is refresh validation when needed. This brings a bunch of other questions with it though, like what to do with the state of existing validators. I still haven't had time to look at this, sorry.

**Comment by t03apt** [comment]
I think I would expect validation controller to be reset when the entity is replaced with another object.

**Comment by RWOverdijk** [comment]
Is it using an array observer? I don't get it. If you change the array, it must trigger an update. I update the array and it just updates here.

**Comment by t03apt** [comment]
I am confused. I think this is the real issue:
> validation does not work because aureliaForm.mapped goes out of sync of aureliaForm.formGroups.

I have just posted a new issue. I think [formGroupsChanged()](https://github.com/SpoonX/aurelia-form/blob/master/src/component/aurelia-form.js#L123) will be triggered properly once this is fixed:
[#196 form-group: repeater should create new formGroup objects when the collection is changed](https://github.com/SpoonX/aurelia-form/issues/196)
