### ISSUE TITLE
form-element: lifecycle events should be triggered for the child element

### ISSUE THREAD

**Issue by t03apt** [SpoonX/aurelia-form#197]
Aurelia is not triggering lifecycle events on the dynamically added custom elements.
See: [TemplatingEngine docs](http://aurelia.io/hub.html#/doc/api/aurelia/templating/latest/class/TemplatingEngine) enhance method
> enhance(): View
Returns
A View representing the enhanced UI. Consumers of this API are responsible for enforcing the View lifecycle.A View representing the enhanced UI. Consumers of this API are responsible for enforcing the View lifecycle.

I think form-element should trigger those on its child element.
I expect all these [lifecycle events](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/creating-components/3) to be trigger properly on my custom element: created, bind, attached, detached, unbind
detached and unbind are never triggered at the moment.

**Comment by t03apt** [comment]
I have created a small gist sample that could be used as a reference.
my-containter is a simplified example of form-group.
See: https://gist.run/?id=dbf04191d963e2cc3a9021c924887c7e

**Comment by t03apt** [comment]
_I have posted a question related to this to aurelia-templating repository. They may reply something useful later. https://github.com/aurelia/templating/issues/540_

**Comment by nmocruz** [comment]
is working!??
![image](https://cloud.githubusercontent.com/assets/944357/24731225/86540724-1a60-11e7-8391-b4e69e57d4b7.png)

**Comment by RWOverdijk** [comment]
Ooh, cool

**Comment by t03apt** [comment]
@nmocruz Yes.
