### ISSUE TITLE
Prevent multiple form submissions

### ISSUE THREAD

**Issue by natrim** [SpoonX/aurelia-form#202]
sometimes you need to prevent <aurelia-from> to being sent twice

now you can disable the submission in the valid event, but you cannot disable the auto submit button

**Comment by RWOverdijk** [comment]
What do you mean? You mean the generated button?

**Comment by natrim** [comment]
yes, you cannot set disabled on the generated button without rewriting it whole with slot
it would help to add buttonDisabled property

but it would be nice to have whole multiple form submission baked in so you don't need to check it in valid event

**Comment by RWOverdijk** [comment]
So it automatically disables on invalid or on sending? The former can be built, the later would be difficult as the form doesn't know when it's done. That would require some additional logic, but I like it :)
