### ISSUE TITLE
novalidate for aurelia-form

### ISSUE THREAD

**Issue by natrim** [SpoonX/aurelia-form#203]
<aurelia-form needs novalidate option or else chrome makes errors:

An invalid form control with name='' is not focusable.

**Comment by RWOverdijk** [comment]
@natrim Could you be more specific? Or better yet, submit a PR? :)

**Comment by natrim** [comment]
aurelia-form needs to have settable attribute novalidate

so <aurelia-form novalidate.bind="true"> generates <form novalidate>

to disable browser validation
