### ISSUE TITLE
Can't type into "form-textarea" input

### ISSUE THREAD

**Issue by thomaskonrad** [SpoonX/aurelia-form#207]
Hi created a `form-textarea´ input via `form-group` like this:

    <form-group name="message" element="textarea" label="Message" required="true" value.bind="message.message"></form-group>

Altough I did not set a `readonly` or `disabled` attribute, the textarea element is not writable. It looks enabled, but when I type something, the characters don't appear. I left all the config values at their defaults.

Any ideas?

**Comment by thomaskonrad** [comment]
It seems that the default value for `maxlength` is interpreted as `0`:

    > var a = document.getElementById('textarea')
    < <textarea name.bind=​"name" value.bind=​"value" placeholder.bind=​"placeholder" autofocus.bind=​"autofocus" cols.bind=​"cols" rows.bind=​"rows" disabled.bind=​"disabled" maxlength.bind=​"maxlength" readonly.bind=​"readonly" required.bind=​"required" wrap.bind=​"wrap" class=​"au-target form-control" au-target-id=​"55" name=​"message" placeholder cols=​"20" rows=​"2" maxlength=​"0" required wrap=​"null" id=​"asdf">​</textarea>​
    > a.maxLength
    < 0

**Comment by RWOverdijk** [comment]
Really? And that's not a problem for regular inputs? That's strange. Is it set to 0 or null internally? Easy fix would then be using undefined instead (which I think it is).

PS: Sorry for the delayed reply. I was on a holiday.

**Comment by thomaskonrad** [comment]
Well, yes, really 😊 No, regular inputs work as expected.

**Comment by RWOverdijk** [comment]
I think they might have different defaults in the components than. Mind making a PR?
