### ISSUE TITLE
Form validation without aurelia-orm?

### ISSUE THREAD

**Issue by thomaskonrad** [SpoonX/aurelia-form#208]
The docs only state an example of form validation using `aurelia-orm`. Is it even possible without `aurelia-orm`? When I try to use it without `aurelia-orm`, I keep getting this when typing anything into any form input:

    Unhandled rejection TypeError: Cannot read property '__rules__' of null

The error happens here:

    define('aurelia-validation/implementation/rules',["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    /**
     * Sets, unsets and retrieves rules on an object or constructor function.
     */
    var Rules = (function () {
        // ...
        /**
         * Retrieves the target's rules.
         */
        Rules.get = function (target) {
            return target[Rules.key] || null; // <-- target is 'null' here.
        };

Any idea what's wrong?

**Comment by RWOverdijk** [comment]
It works with whatever entity provided having validation rules. Entities are just objects, but they need rules. Read the docs here: https://aurelia-form.spoonx.org/cookbook/setting-up-validation.html#usage-example
