### ISSUE TITLE
Basic running example

### ISSUE THREAD

**Issue by danice** [SpoonX/aurelia-form#26]
Sorry but I could not get it working with the 'skeleton-typescript-webpack'...
Could be possible to have some simple examples working for example with the aurelia skeleton projects?

**Comment by doktordirk** [comment]
ah, sorry. it.s not configured for that yet. will do that asap

**Comment by bas080** [comment]
@danice, There is a quite extensive example of aurelia-form here
https://github.com/bas080/swan-example-client/tree/form-example/src/scripts/page/form
It's not typescript though. Hope this helps you for now.

**Comment by danice** [comment]
@bas080  Thanks! I will check it...
