### ISSUE TITLE
To "fix"

### ISSUE THREAD

**Issue by RWOverdijk** [SpoonX/aurelia-form#4]
- **Fix view-manager (it accepts weird paths. `../` where it should be `./`**
- Rename attribute to element (where applicable)
- Rename plural directories to singular
- Make framework the not-root directory (move it in view? Donno)
- Allow overriding components as well
- Remove fieldset from schema-form
- Simplify directory structure

**Comment by bas080** [comment]
@RWOverdijk 
Overriding components is what the aurelia's `compose` element does enable us to do. It might make sense to move that logic to view manager and a have a custom element with the name.

``` html
<resolved-component namespace="form" view="input"></resolved-component>
```

Somewhere in the configurations one would have to define a map that matches every `view` with a Constructor.

**Comment by RWOverdijk** [comment]
@bas080 All done?

**Comment by bas080** [comment]
@RWOverdijk, The view manager related task is not done. Relative paths are relative to the component itself. Example:

> example of an absolute path.

``` js
    .plugin('aurelia-view-manager', view => {
      view.configureNamespace('spoonx/form', {
        map: {
          text: '/dist/info.html'
        }
      });
    })
```

> example of a relative path where component location is. `component/input.js`

``` js
      .plugin('aurelia-view-manager', view => {
      view.configureNamespace('spoonx/form', {
        map: {
          text: '../other/input.html'
        }
      });
    })
```

The input component will look for it's view in `component/../other/input.html`
