### ISSUE TITLE
Unable to resolve aurelia-form/component

### ISSUE THREAD

**Issue by intelinc** [SpoonX/aurelia-form#49]
I have been trying to get aurelia-form to work with the aurelia skeleton for webpack (both versions). On a fresh skeleton project I add aurelia-form and aurelia-view-manager to the package.json dependencies,  npm install, and then npm start. The app runs without errors, but webpack states:

> Unable to resolve aurelia-form/component

 This is without the plugin actually being pulled in via main.js. If I do try and add the plugin, the browser throws a javascript error: 

> Unhandled rejection Error: Cannot find module './aurelia-form/component/entity-form'. 

 I've tried various ways of resolving the module files search settings, but all to no avail, and given the fact that webpack complains on a virgin install (even though it seems to build) , I'm thinking something else must be wrong. Is there some installation trick I'm missing, or is this maybe an issue with the webpack variants of the aurelia skeleton projects?

**Comment by doktordirk** [comment]
probably need like "aurelia-form/component" in your webpack config. or you.ll wait a day and i fixup the package

**Comment by doktordirk** [comment]
@intelinc should work now

**Comment by intelinc** [comment]
Thanks, taking a look now.
