### ISSUE TITLE
FormGroup <label> not associated with <input>

### ISSUE THREAD

**Issue by ppvg** [SpoonX/aurelia-form#52]
When using a `form-group` to wrap a control element (e.g. an `<input>`), the element is not explicitly "labeled", i.e. the label does not have a `for` attribute pointing to the control element's `id`. Explicit labeling allows users to interact with the label to focus the control element.

This is a usability issue which affects both "normal" users and users with screen readers.

Checkboxes and radios use contained control elements, so those are fine.

**Comment by bas080** [comment]
Anyone working on this? Could this issue be assigned to me?
