### ISSUE TITLE
 [aurelia-form] an element key propery cannot be null or undefined

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-form#74]
That's should not apply for buttons? if add add one, it's used as label (which i don't want), and if i set it to '' i still get that error

**Comment by bas080** [comment]
You might actually want it. BTW, in the latest build it does not give an error but a debug message instead.

https://github.com/SpoonX/aurelia-form/blob/957a980cdb7fcec660fcb43836718b40e7776935/src/component/form-field.js#L30

The reason why you might want to pass a key has to do with the callback one gets in the `actions: [{ action: (item, index, items) => {...}}]`

Here you can see function being called with the value property of the formField viewmodel.
https://github.com/SpoonX/aurelia-form/blob/master/src/component/framework/bootstrap/actions.html

**Comment by doktordirk** [comment]
what i mean, is that the key is displayed as label, and i don't want that for sure

displays 'login-key'

``` js
 {
        key    : 'login-key',
        type   : 'buttons',
        actions: [{
          label     : 'Login',
          action    : this.login,
          attributes: {
            class: 'btn btn-primary'
          }
        }]
      }
```
