### ISSUE TITLE
Unhandled rejection TypeError in Internet Explorer 11 & Firefox 47

### ISSUE THREAD

**Issue by beatsm** [SpoonX/aurelia-form#77]
Hi

Can run this in IE 11 or Firefox 47.0.1

Receive the following error Unable to get property 'key' of undefined or null reference in IE and Unhandled rejection TypeError: element is undefined in Firefox. 

Works fine in Chrome.

**Comment by doktordirk** [comment]
confirmed for firefox

**Comment by doktordirk** [comment]
fixed with the next version
