### ISSUE TITLE
Switch to aurelia-validation

### ISSUE THREAD

**Issue by dkent600** [SpoonX/aurelia-form#82]
Feature request:  Support the new aurelia-validation.  I'm not gonna use aurelia-form until this is adopted.

**Comment by doktordirk** [comment]
validation doesn't support nested properties yet and they are really nested here. but we'll either find a way or validation does support them eventually

**Comment by bas080** [comment]
@dkent600, What is it that you mean with support for the new aurelia-validation?

Aurelia-form only mutates the model. You can perform validation on that mutated model no problem.

I like your compact way of communicating and I look forward to your short definition of "support the new aurelia-validation".

**Comment by doktordirk** [comment]
@bas080 atm it has validatejs code in it, and validation with the new version i only managed to to it manually. the & validate and the binding for the renderer doesn.t work

**Comment by doktordirk** [comment]
some working proposal https://github.com/SpoonX/aurelia-form/pull/93

**Comment by afmuller** [comment]
Any progress on this issue? Also interested in using aurelia-form. However, would like to use the newer 'aurelia-validation' and not the deprecated 'aurelia-validatejs'.

**Comment by RWOverdijk** [comment]
@afmuller We'll look into it. We'll have to either stop depending on it, or update and support the new version. Because of aurelia-orm also allowing the use of validation, it makes sense to update them. @bas080  and @doktordirk, could you look into this?

**Comment by RWOverdijk** [comment]
This ticket is being closed now due to added support in our next version. Any questions? Feel free to ask :)
